table Partidos_1930_2022
	lineageTag: 327c16f6-6759-48a9-997d-0f3c465dacbb

	column Equipo_1
		dataType: string
		lineageTag: 6235ef93-a15a-4937-a782-f70d621ddf79
		summarizeBy: none
		sourceColumn: Equipo_1

		annotation SummarizationSetBy = Automatic

	column Equipo_2
		dataType: string
		lineageTag: d08fe68e-f739-4339-af7a-366bb3f9eb7a
		summarizeBy: none
		sourceColumn: Equipo_2

		annotation SummarizationSetBy = Automatic

	column Goles_Equipo_1
		dataType: int64
		formatString: 0
		lineageTag: 3ebec28a-fb71-4a11-ad36-868b0ab608cf
		summarizeBy: sum
		sourceColumn: Goles_Equipo_1

		annotation SummarizationSetBy = Automatic

	column Goles_Equipo_2
		dataType: int64
		formatString: 0
		lineageTag: bb709c15-8e93-4954-aabe-b2dae3566d91
		summarizeBy: sum
		sourceColumn: Goles_Equipo_2

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: c4d56925-81ef-4cfc-bfaa-d50d3625a88a
		summarizeBy: none
		sourceColumn: Fecha

		variation Variación
			isDefault
			relationship: ee12dadf-3018-42b5-befb-0179b7b68e60
			defaultHierarchy: LocalDateTable_4b34d9cd-cecb-42f3-a8b2-e3724e0d0907.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Año
		dataType: int64
		formatString: 0
		lineageTag: 99a6725b-08a2-45f8-af95-3ef54110f277
		summarizeBy: none
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	partition Partidos_1930_2022 = m
		mode: import
		source =
				let
				  Origen = Csv.Document(File.Contents("D:\OneDrive\Desktop\Dashborad Mundial Futbol\dataset\matches_1930_2022.csv"), [Delimiter = ",", Columns = 44, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				  #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars = true]),
				  #"Tipo de columna cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos", {{"home_team", type text}, {"away_team", type text}, {"home_score", Int64.Type}, {"home_xg", Int64.Type}, {"home_penalty", Int64.Type}, {"away_score", Int64.Type}, {"away_xg", Int64.Type}, {"away_penalty", Int64.Type}, {"home_manager", type text}, {"home_captain", type text}, {"away_manager", type text}, {"away_captain", type text}, {"Attendance", Int64.Type}, {"Venue", type text}, {"Officials", type text}, {"Round", type text}, {"Date", type date}, {"Score", type text}, {"Referee", type text}, {"Notes", type text}, {"Host", type text}, {"Year", Int64.Type}, {"home_goal", type text}, {"away_goal", type text}, {"home_goal_long", type text}, {"away_goal_long", type text}, {"home_own_goal", type text}, {"away_own_goal", type text}, {"home_penalty_goal", type text}, {"away_penalty_goal", type text}, {"home_penalty_miss_long", type text}, {"away_penalty_miss_long", type text}, {"home_penalty_shootout_goal_long", type text}, {"away_penalty_shootout_goal_long", type text}, {"home_penalty_shootout_miss_long", type text}, {"away_penalty_shootout_miss_long", type text}, {"home_red_card", type text}, {"away_red_card", type text}, {"home_yellow_red_card", type text}, {"away_yellow_red_card", type text}, {"home_yellow_card_long", type text}, {"away_yellow_card_long", type text}, {"home_substitute_in_long", type text}, {"away_substitute_in_long", type text}}, "es"),
				    #"Otras columnas quitadas" = Table.SelectColumns(#"Tipo de columna cambiado",{"home_team", "away_team", "home_score", "away_score", "Date", "Year"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Otras columnas quitadas",{{"home_team", "Equipo_1"}, {"away_team", "Equipo_2"}, {"home_score", "Goles_Equipo_1"}, {"away_score", "Goles_Equipo_2"}, {"Date", "Fecha"}, {"Year", "Año"}}),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Columnas con nombre cambiado","West Germany","Germany",Replacer.ReplaceText,{"Equipo_1"}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado","Germany DR","Germany",Replacer.ReplaceText,{"Equipo_1"}),
				    #"Valor reemplazado2" = Table.ReplaceValue(#"Valor reemplazado1","West Germany","Germany",Replacer.ReplaceText,{"Equipo_2"}),
				    #"Valor reemplazado3" = Table.ReplaceValue(#"Valor reemplazado2","Germany DR","Germany",Replacer.ReplaceText,{"Equipo_2"})
				in
				    #"Valor reemplazado3"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

